#index:
blog_list:
    path: /blog
    controller: App\Controller\BlogController::list

     # if the action is implemented as the __invoke() method of the
    # controller class, you can skip the '::method_name' part:
    # controller: App\Controller\BlogController
